Update update-grubefi

diff --git a/update-grubefi b/update-grubefi
--- a/update-grubefi
+++ b/update-grubefi
@@ -5,42 +5,40 @@
 #
 
 USERID=`id -u`
-if [ $USERID -ne 0 ]; then
-   echo "Error: You must run this as root or with sudo"
-   exit
-fi
+if [ $USERID -eq 0 ]; then
+   cp /boot/efi/config.txt.uefi /boot/efi/config.txt
+   echo "dtoverlay=disable-bt" >> /boot/efi/config.txt
+   echo "" >> /boot/efi/config.txt
+   cat /boot/config.txt >> /boot/efi/config.txt
 
-cp /boot/efi/config.txt.uefi /boot/efi/config.txt
-echo "dtoverlay=disable-bt" >> /boot/efi/config.txt
-echo "" >> /boot/efi/config.txt
-cat /boot/config.txt >> /boot/efi/config.txt
+   #sed -i -e 's/^uart_2ndstage=1/#uart_2ndstage=1/' /boot/efi/config.txt
+   #sed -i -e 's/^dtoverlay=miniuart-bt/#dtoverlay=miniuart-bt/' /boot/efi/config.txt
 
-#sed -i -e 's/^uart_2ndstage=1/#uart_2ndstage=1/' /boot/efi/config.txt
-#sed -i -e 's/^dtoverlay=miniuart-bt/#dtoverlay=miniuart-bt/' /boot/efi/config.txt
+   sed -i -e '/^initramfs/d' /boot/efi/config.txt
+   sed -i -e '/^kernel=/d' /boot/efi/config.txt
 
-sed -i -e '/^initramfs/d' /boot/efi/config.txt
-sed -i -e '/^kernel=/d' /boot/efi/config.txt
+   cp --preserve=timestamps /boot/bcm2711-rpi-400.dtb /boot/efi/
+   cp --preserve=timestamps /boot/bcm2711-rpi-4-b.dtb /boot/efi/
+   cp --preserve=timestamps /boot/bcm2711-rpi-cm4.dtb /boot/efi/
 
-cp --preserve=timestamps /boot/bcm2711-rpi-400.dtb /boot/efi/
-cp --preserve=timestamps /boot/bcm2711-rpi-4-b.dtb /boot/efi/
-cp --preserve=timestamps /boot/bcm2711-rpi-cm4.dtb /boot/efi/
-
-cp -r --preserve=timestamps /boot/overlays /boot/efi/
-
-if [ -d /boot/firmware ]; then
-   cp -r --preserve=timestamps /boot/firmware /boot/efi/
-fi
-
-ARGS=`sed 's/^root=.\+ rw //' /boot/cmdline.txt`
-NEW_CMDLINE="GRUB_CMDLINE_LINUX=\"${ARGS}\""
-CUR_CMDLINE=`grep "^GRUB_CMDLINE_LINUX=" /etc/default/grub`
-
-if [ "$CUR_CMDLINE" != "$NEW_CMDLINE" ]; then
-   sed -i -e "s/^GRUB_CMDLINE_LINUX=.*/${NEW_CMDLINE}/" /etc/default/grub
-   grub-mkconfig -o /boot/efi/grub/grub.cfg
-   if [ $? -ne 0 ]; then
-      echo "Error: failed to successfully run grub-mkconfig"
+   cp -r --preserve=timestamps /boot/overlays /boot/efi/
+   if [ -d /boot/firmware ]; then
+      cp -r --preserve=timestamps /boot/firmware /boot/efi/
    fi
-fi
 
-sync
+   ARGS=`sed 's/^root=.\+ rw //' /boot/cmdline.txt`
+   NEW_CMDLINE="GRUB_CMDLINE_LINUX=\"${ARGS}\""
+   CUR_CMDLINE=`grep "^GRUB_CMDLINE_LINUX=" /etc/default/grub`
+
+   if [ "$CUR_CMDLINE" != "$NEW_CMDLINE" ]; then
+      sed -i -e "s/^GRUB_CMDLINE_LINUX=.*/${NEW_CMDLINE}/" /etc/default/grub
+      grub-mkconfig -o /boot/efi/grub/grub.cfg
+      if [ $? -ne 0 ]; then
+         echo "Error: failed to successfully run grub-mkconfig"
+      fi
+   fi
+
+   sync
+else
+   echo "Error: You must run this as root or with sudo"
+fi
