Update update-grubefi
Added filesystem syncs

diff --git a/update-grubefi b/update-grubefi
--- a/update-grubefi
+++ b/update-grubefi
@@ -5,15 +5,20 @@
 #
 
 cp /boot/efi/config.txt.uefi /boot/efi/config.txt
+sync
 echo "dtoverlay=disable-bt" >> /boot/efi/config.txt
+sync
 echo "" >> /boot/efi/config.txt
 cat /boot/config.txt >> /boot/efi/config.txt
+sync
 
 #sed -i -e 's/^uart_2ndstage=1/#uart_2ndstage=1/' /boot/efi/config.txt
 #sed -i -e 's/^dtoverlay=miniuart-bt/#dtoverlay=miniuart-bt/' /boot/efi/config.txt
 
 sed -i -e '/^initramfs/d' /boot/efi/config.txt
+sync
 sed -i -e '/^kernel=/d' /boot/efi/config.txt
+sync
 
 cp --preserve=timestamps /boot/bcm2711-rpi-400.dtb /boot/efi/
 cp --preserve=timestamps /boot/bcm2711-rpi-4-b.dtb /boot/efi/
@@ -24,6 +29,7 @@ cp -r --preserve=timestamps /boot/overlays /boot/efi/
 if [ -d /boot/firmware ]; then
    cp -r --preserve=timestamps /boot/firmware /boot/efi/
 fi
+sync
 
 ARGS=`sed 's/^root=.\+ rw //' /boot/cmdline.txt`
 NEW_CMDLINE="GRUB_CMDLINE_LINUX=\"${ARGS}\""
@@ -31,5 +37,10 @@ CUR_CMDLINE=`grep "^GRUB_CMDLINE_LINUX=" /etc/default/grub`
 
 if [ "$CUR_CMDLINE" != "$NEW_CMDLINE" ]; then
    sed -i -e "s/^GRUB_CMDLINE_LINUX=.*/${NEW_CMDLINE}/" /etc/default/grub
+   sync
    grub-mkconfig -o /boot/efi/grub/grub.cfg
+   if [ $? -ne 0 ]; then
+      echo "Error: failed to successfully run grub-mkconfig"
+   fi
 fi
+sync
